### ISSUE TITLE
csv file drop

### ISSUE THREAD

**Issue by Schubidu** [finanzcheck/wheel-of-fortune#5]
As a json file we will drop a csv file

**Comment by aklinkert** [comment]
That csv file has to be in a specific format to ensure correct import. Any ideas how to solve that common csv problem?

**Comment by Schubidu** [comment]
Let's take the default Excel-export file format with `;`-seperator. The first row is reserved for column names. Be flexible in columns order `name;spokes` is also valide as `spokes;names`

Do some validation steps
1. drop a valid json or a csv in valid format, import the file
2. drop an unkown file-format, show a message to hint which files and formats we support
3. drop a csv in a not support format, show same message as above
